# Generated by Django 3.2.7 on 2021-11-25 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
                ('reason', models.CharField(max_length=100)),
                ('worthit', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('recurring', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], max_length=1)),
                ('paid', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], max_length=1)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.month')),
            ],
        ),
    ]
