# Generated by Django 3.2.7 on 2021-11-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211126_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='reason',
            field=models.TextField(max_length=300),
        ),
    ]
